# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "tannal"
weight = 1
contentDir = "content/en"

[zh-cn]
languageName = "Chinese"
languagedirection = "ltr"
title = "谭盟"
weight = 2
contentDir = "content/zh-cn/"
